#server:
#  port: 36200
filesystem:
  storage-dir: '/home/emari/Documents/fs-rest-api/testStorage'
spring:
  jackson:
    default-property-inclusion: non_null
logging:
  level:
    root: info
    org.springframework.web: debug